version: "3.4"

services:
  app:
    build:
      context: ./demo
      dockerfile: Dockerfile
    volumes:
      - ./demo:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 28000:8000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "my_database"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
    ports:
      - 25432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/ # Docker managed volume
      # - /path/to/your/database:/var/lib/postgresql/data # User managed volume

volumes:
  postgres:
